apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/yoschihirokaimoto/ray-argocd-example.git"
    targetRevision: HEAD
    path: apps/kuberay/ray-service
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ray-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true